### ISSUE TITLE
Possible to support nested comments

### ISSUE THREAD

**Issue by benfrain** [yisibl/sublime-perfectionist#5]
I'm using this in Sublime (in case that is relevant). Given a rule like this (removed some properties for brevity):

```scss
.bb-Choices_Label {
    display: inline-flex;
    align-items: center;
    /*This is the underline*/
    &:before {
        content: "";
        position: absolute;
    }
    /*This is the nib*/
    &:after {
        [aria-selected="true"] & {
            position: absolute;
            top: 100%;
        }
    }
}
```

Perfectionist is generating this:

```scss
.bb-Choices_Label {
    display: inline-flex;
    align-items: center;
    /*This is the underline*/

    &:before {
        content: "";
        position: absolute;
    }/*This is the nib*/

    &:after {
        [aria-selected="true"] & {
            position: absolute;
            top: 100%;
        }
    }
}
```

Would it be possible to retain the position of nested comments with regards to nested selectors. I realise I'm using a non-standard syntax!
